#!/usr/bin/env ruby

require "rake"
require "pry"

def read_files(glob)
  `ls #{glob}`.split("\n").sort_by do |file|
    str_to_int(file)
  end
end

def str_to_int(str)
  str.split(/\D/).reject { |d| d.empty? }.join("").to_i
end

unionfiles     = read_files("*.union")
connectedfiles = read_files("*.connected")
testfiles      = unionfiles.zip(connectedfiles)

testfiles.each do |testfiles|
  unionfile     = testfiles[0]
  connectedfile = testfiles[1]
  count         = str_to_int(unionfile)

  puts "Test: #{count}"

  sh "cat #{unionfile} connected #{connectedfile} | java Main"
end
